name: generate_site

on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: true  # Fetch Hugo themes (true OR recursive)
                fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

            - name: Hugo setup
              uses: peaceiris/actions-hugo@v2
              with:
                  # The Hugo version to download (if necessary) and use. Example: 0.58.2
                  hugo-version: latest # optional, default is latest
                  # Download (if necessary) and use Hugo extended version. Example: true
                  extended: true # optional, default is false

            # Runs a set of commands using the runners shell
            - name: Generate Hugo site
              run: hugo --minify

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                publish_dir: ./public